### ISSUE TITLE
Configure jenkins  to use Github Pull Request Builder Plugin

### ISSUE THREAD

**Issue by anthonime** [gwtd3/gwt-d3#107]
It allows jenkins to build a pull request made on github before to check if it can be safely merged.

**Comment by ericcitaire** [comment]
I made a test with BuildHive, at CloudBees. Almost nothing to configure, it's perfect. Seems to work fine for now.
To be continued...

**Comment by ericcitaire** [comment]
I'm currently adding Travis CI support as well.

**Comment by ericcitaire** [comment]
Travis is doing everything for us, I'm closing this issue.
