### ISSUE TITLE
Is it possible to use gwt-d3 for Spring applications?

### ISSUE THREAD

**Issue by samvel-malintsyan** [gwtd3/gwt-d3#141]
Hi, 
Is it possible to use gwt-d3 for Spring applications?
Thanks,
Samvel

**Comment by MdSE** [comment]
Hi @smalints ,

Yes, its possible. I work in a project that GWT-d3 and Spring Boot.

Marco

**Comment by ericcitaire** [comment]
Spring is server-side, while GWT is client-side.

There is no problem using Spring and gwt-d3 in the same project.
